name: .NET Core Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ClueGame.Core

      - name: Build Core Library
        run: dotnet build ClueGame.Core --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ClueGame.Core.Tests --no-restore --verbosity normal